### ISSUE TITLE
WebServices broken in Bugzilla 4.4

### ISSUE THREAD

**Issue by MarkMaldaba** [bayoteers/AgileTools#17]
Bugzilla 4.4 introduced the concept of a white-list for the WebServices API, so any method not explicitly listed is blocked from being accessed.

This means that none of the WebServices in AgileTools are currently working on Bugzilla 4.4.  It is also possible that other Bugzilla versions are affected, as it looks like this was backported to earlier versions, too.

This was introduced by Mozilla in bug 1090275 [https://bugzilla.mozilla.org/show_bug.cgi?id=1090275]

The 'Example' extension in Bugzilla was fixed by adding the following to the top of its WebServices.pm file:
````perl
use constant PUBLIC_METHODS => qw(
    hello
    throw_an_error
);
````
Obviously in AgileTools there are multiple such files, so the solution is a little more detailed, but the principle is the same.

**Comment by keto** [comment]
Yep, I think this came in 4.4.7 or 4.4.8. Haven't had time to update yet, but I'll try to fix this as soon as possible... PRs also welcome :)

**Comment by MarkMaldaba** [comment]
>  PRs also welcome

Done!  Sorry that it seems to have created quite a lot of spam in the ticket!

**Comment by keto** [comment]
Thank you! Still need to fix the few webservice methods in the other extensions, but this helped a lot.
