### ISSUE TITLE
'Agile.Pool.get' not found error in planning interface

### ISSUE THREAD

**Issue by kevinjansz** [bayoteers/AgileTools#19]
On attempting to use the 'Planning' interface the JSON RPC calls are getting the following response message: 

    {
      "error": {
        "message": "The requested method 'Agile.Pool.get' was not found.",
        "code": 67399.0
      },
      "id": 1.0,
      "result": null
    }

The message is then reported in a popup on screen. I was hoping to get some troubleshooting clues. 
Bugzilla version: 4.2.13

**Comment by MarkMaldaba** [comment]
Are you using the latest version of AgileTools?  It is likely that you are experiencing issue #17, which has recently been fixed.

**Comment by keto** [comment]
Yes, that is the most likely reason. If the issue persist after updating the AgileTools from master branch, please reopen

**Comment by kevinjansz** [comment]
Thanks for the quick reply - confirmed, resolved in the master. 
Looks good.
