### ISSUE TITLE
Uncertain how to end a sprint - and start the next

### ISSUE THREAD

**Issue by kevinjansz** [bayoteers/AgileTools#20]
This is a question rather than issue - but successfully I've managed to make a sprint; pull in items from the backlog; have those items resolved and then closed. 

The current sprint is still active - I'm uncertain what actions to take to end this and get access to create/start the next sprint. Any pointers would be much appreciated. 

It's possible this would be best covered by some brief walk-thru notes/screenshots (#15).

**Comment by keto** [comment]
The basic workflow is that
1. Add items to sprint (planning)
2. Commit to the sprint (button below the sprint in the planning view)
3. Work on the items in the sprint
4. Close the sprint when it ends (button where the commit button was earlier)

When you close the sprint it will ask you the info for the next sprint and create that automatically. Any unresolved items in the current sprint will be moved to this new sprint.

And yes, a short user documentation would be much needed, but unfortunately I haven't had time to write that.

**Comment by kevinjansz** [comment]
Perfect, thanks again. 

* Commit = start the sprint
(can't end the sprint until you've started it)
* Close = end the sprint + get the popup dialog to Define the next sprint
