### ISSUE TITLE
 Amninistration/Parameters/AgileTools error:

### ISSUE THREAD

**Issue by sandrinococo** [bayoteers/AgileTools#22]
I try to view Amninistration/Parameters/AgileTools and i found the error:

>URL : http://localhost/ediparams.cgi?section=agiletools
>undef error - Can't use string ("ARRAY(0x85ddad0)") as an ARRAY ref while "strict refs" is use at >Bugzilla/Template.pm line 1013.

Why?

=======================
SO: ubuntu 14.04
Bugzilla : 5.0
AgileTools : branch : master
BayotBase : branch : master

**Comment by sandrinococo** [comment]
I've found an error on file: lib/Params.pm

I've commented two parameters 'agile_check_time_severity' 'agile_check_time_resolution' because the multichoice has an error on field "choices". With this the page works fine : 

---

        # TODO REMOVED *** END
        # cause errors in bugzilla 5.0
        # page /editparams.cgi?section=agiletools
        # undef error - Can't use string ("") as an ARRAY ref while "strict refs" in use at Bugzilla/Template.pm line 1013. 
  #        {
  #            name => 'agile_check_time_severity',
  #            desc => 'Bug severities for which time worked is checked when resolving',
  #            type    => 'm',
  #            choices => get_legal_field_values('bug_severity'),
  #            default => [],
  #        },
  #        {
  #            name => 'agile_check_time_resolution', 
  #            desc => 'Bug resolutions for which time worked is checked when resolving',
  #            type    => 'm',
  #            choices => get_legal_field_values('resolution'),
  #            default => [], 
  #        },
        # TODO REMOVED *** END

---

**Comment by sandrinococo** [comment]
I try to view /page.cgi?id=agiletools/scrum/planning.html&team_id=<item id> and i found the error:

Error: Can't locate object method "_user_to_hash" via package "Bugzilla::WebService::Server::JSONRPC::Bugzilla::Extension::AgileTools::WebService::Team" at Bugzilla/WebService/Bug.pm line 1227.

Why?

SO: ubuntu 14.04
Bugzilla : 5.0
AgileTools : branch : master
BayotBase : branch : master

**Comment by keto** [comment]
This is basically because I haven't had time to adapt the code to changes in Bugzilla 5.0 yet. I'll try to find some time to do that in the near future.

**Comment by keto** [comment]
The admin parameters related error is a Bugzilla bug https://bugzilla.mozilla.org/show_bug.cgi?id=1227455
Hopefully the patch gets accepted and included in the next bugzilla release.

I created separate issue #23 for the other Bugzilla 5.0 adaptation and fixes
